In [45]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.common.exceptions import ElementNotInteractableException
#Importing requests
import requests

# importing regex
import re

In [46]:
PATH = 'C:\Program Files (x86)\chromedriver.exe'                         #chromedriver_win32
driver = webdriver.Chrome(r"C:\\Users\\hp\\Downloads\\chromedriver.exe")

<ipython-input-46-5cece3282b53>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\\Users\\hp\\Downloads\\chromedriver.exe")

In [47]:
#website url CARS24
driver.get("https://www.cars24.com/?utm_source=google&utm_medium=cpc&utm_campaign=brand&utm_source=google&utm_medium=adwords&utm_keyword=cars24&utm_matchtype=e&utm_device=c&adgroup_id=125126138842&campaign_id=1781126778&gclid=CjwKCAiAxJSPBhAoEiwAeO_fP6LKHqmdAZ2OOWvB2VYE-45zxyUrjdTK2pGSJsx51bzydKDWvFg6xxoC5o0QAvD_BwE&gclid=CjwKCAiAxJSPBhAoEiwAeO_fP6LKHqmdAZ2OOWvB2VYE-45zxyUrjdTK2pGSJsx51bzydKDWvFg6xxoC5o0QAvD_BwE")

In [48]:
#cancelling pop up
button_click=driver.find_element_by_xpath("//div[@class='float-right TBxAN']/img")
button_click.click()

time.sleep(1)

#clicking used cars options
used_car_button=driver.find_element_by_xpath("//ul[@class='float-right _1yq3e']/li[3]/a")
used_car_button.click()

time.sleep(0.5)

<ipython-input-48-717ecaaaa2bb>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  button_click=driver.find_element_by_xpath("//div[@class='float-right TBxAN']/img")
<ipython-input-48-717ecaaaa2bb>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  used_car_button=driver.find_element_by_xpath("//ul[@class='float-right _1yq3e']/li[3]/a")

In [28]:
used_car_button=driver.find_element_by_xpath("//ul[@class='float-right _1yq3e']/li[3]/a")
used_car_button.click()

<ipython-input-28-8ae4c01cbde8>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  used_car_button=driver.find_element_by_xpath("//ul[@class='float-right _1yq3e']/li[3]/a")

In [23]:
dropdown_b=driver.find_element_by_xpath("//div[@class='_2MBbu']/a/img")
dropdown_b.click()

<ipython-input-23-3f805438941a>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dropdown_b=driver.find_element_by_xpath("//div[@class='_2MBbu']/a/img")

In [29]:
#//label[@for='LH']
dropdown_b=driver.find_element_by_xpath("//li[@class='ykp-v'][6]/div/img")
dropdown_b.click()

<ipython-input-29-f8f06e0a04ee>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dropdown_b=driver.find_element_by_xpath("//li[@class='ykp-v'][6]/div/img")

In [152]:
filter1=driver.find_element_by_xpath("//ul[@class='sVtBG _7AhJm']/li[1]/div/span[1]/img")
filter1.click()

time.sleep(1)
button_c= driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")
button_c.click()

<ipython-input-152-66fbc95ae925>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  filter1=driver.find_element_by_xpath("//ul[@class='sVtBG _7AhJm']/li[1]/div/span[1]/img")
<ipython-input-152-66fbc95ae925>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  button_c= driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")

In [32]:
a=driver.find_element_by_xpath("//div[@class='v590M']/img")
a.click()

<ipython-input-32-5ccbda9cfbb4>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  a=driver.find_element_by_xpath("//div[@class='v590M']/img")

In [6]:
#new delhi:
# 1. Hatched

#Hatched filter:
filter1=driver.find_element_by_xpath("//ul[@class='sVtBG _7AhJm']/li[1]/div/span[1]/img")
filter1.click()

time.sleep(1)
button_c= driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")
button_c.click()

time.sleep(1)

#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

<ipython-input-6-446c2ee02e24>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  filter1=driver.find_element_by_xpath("//ul[@class='sVtBG _7AhJm']/li[1]/div/span[1]/img")
<ipython-input-6-446c2ee02e24>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  button_c= driver.find_element_by_xpath("//button[@class='btn _3BmFU AgO6q']")

In [5]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [6]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


NDel1=pd.DataFrame({'Model Year': model_num[0:640],'Brand': brand[0:640],
                 'Car Name': name[0:640],'Variant': variant[0:640],'Distance Travelled': distance[0:640],
                 'Number of Owners': owner[0:640],'fuel type': fuel_type[0:640],'Price': price[0:640]})

<ipython-input-6-2782da2e2873>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-6-2782da2e2873>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-6-2782da2e2873>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-6-2782da2e2873>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
<ipython-input-6-2782da2e2873>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-6-2782da2e2873>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-6-2782da2e2873>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-6-2782da2e2873>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [7]:
NDel1

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift Dzire,Manual,118117,1st,Diesel,316399
1,2016,Renault,Kwid,Manual,46028,2nd,Petrol,277599
2,2013,Maruti,Swift,Manual,114506,1st,Diesel,341599
3,2014,Maruti,Ritz,Manual,43382,1st,Diesel,344199
4,2013,Hyundai,i20,Manual,64361,1st,Diesel,355799
...,...,...,...,...,...,...,...,...
635,2017,Maruti,Vitara Brezza,Manual,79494,1st,Diesel,577637
636,2017,Maruti,Ertiga,Manual,118264,1st,Diesel,657999
637,2017,Maruti,Wagon R 1.0,Manual,40513,1st,Petrol,394199
638,2019,Maruti,Alto,Manual,43183,1st,Petrol,289099
639,2017,Maruti,Alto 800,Manual,46246,1st,Petrol,299199

In [13]:
len(NDel1)

640

# Ahmedabad:

In [8]:
# II. Ahmedabad location
loc2=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[1]/a")
loc2.click()

<ipython-input-8-ddd2eb84216b>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc2=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[1]/a")

In [9]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [10]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
car_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Ahmed1=pd.DataFrame({'Model Year': model_num[0:380],'Brand': brand[0:380],
                 'Car Name': name[0:380],'Variant': variant[0:380],'Distance Travelled': distance[0:380],
                 'Number of Owners': owner[0:380],'fuel type': fuel_type[0:380],'Price': price[0:380]})

<ipython-input-10-786df29579ed>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-10-786df29579ed>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-10-786df29579ed>:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-10-786df29579ed>:49: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-10-786df29579ed>:60: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-10-786df29579ed>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-10-786df29579ed>:83: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-10-786df29579ed>:94: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [11]:
Ahmed1

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2018,Maruti,Wagon R 1.0,Manual,13779,1st,Petrol,413399
1,2018,Maruti,Swift,Manual,80785,1st,Petrol,504999
2,2018,Maruti,Alto 800,Manual,52303,1st,Petrol,304499
3,2015,Honda,Brio,Manual,75168,1st,Petrol,392199
4,2019,Maruti,Alto 800,Manual,53590,1st,Petrol,322399
...,...,...,...,...,...,...,...,...
375,2019,Maruti,Alto,Manual,4927,1st,Petrol,297699
376,2018,Ford,Ecosport,Manual,30271,1st,Petrol,857599
377,2020,Maruti,Eeco,Manual,4280,1st,Petrol,421999
378,2020,Maruti,Eeco,Manual,9355,1st,Petrol,421999
379,2020,Maruti,Eeco,Manual,4984,1st,Petrol,421999

In [12]:
len(Ahmed1)

380

In [15]:
# III. Bangalore location
loc3=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[2]/a")
loc3.click()

<ipython-input-15-cb4db83a7090>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc3=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[2]/a")

In [16]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [18]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
car_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Bengl1=pd.DataFrame({'Model Year': model_num[0:435],'Brand': brand[0:435],
                 'Car Name': name[0:435],'Variant': variant[0:435],'Distance Travelled': distance[0:435],
                 'Number of Owners': owner[0:435],'fuel type': fuel_type[0:435],'Price': price[0:435]})

<ipython-input-18-b4c88905686e>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-18-b4c88905686e>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-18-b4c88905686e>:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-18-b4c88905686e>:49: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-18-b4c88905686e>:60: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-18-b4c88905686e>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-18-b4c88905686e>:83: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-18-b4c88905686e>:94: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [19]:
Bengl1

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2014,Hyundai,Grand i10,Manual,38708,1st,Petrol,382299
1,2016,Hyundai,Elite i20,Manual,43221,2nd,Diesel,683299
2,2012,Skoda,Rapid,Manual,88705,2nd,Petrol,486499
3,2016,Maruti,Baleno,Manual,34417,1st,Petrol,705399
4,2015,Hyundai,Elite i20,Manual,53045,1st,Petrol,658599
...,...,...,...,...,...,...,...,...
430,2015,Maruti,Celerio,Automatic,27369,2nd,Petrol,441099
431,2019,Hyundai,NEW SANTRO,Manual,31026,1st,Petrol,565599
432,2013,Maruti,Swift,Manual,26021,1st,Petrol,513299
433,2015,Hyundai,Grand i10,Manual,57741,1st,Petrol,494299
434,2013,Nissan,Terrano,Manual,141578,2nd,Diesel,584399

In [20]:
len(Bengl1)

435

In [21]:
# IV. Chennai location
loc4=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[3]/a")
loc4.click()

<ipython-input-21-5ddd1195d2d2>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc4=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[3]/a")

In [22]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [23]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
car_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Chenna=pd.DataFrame({'Model Year': model_num[0:495],'Brand': brand[0:495],
                 'Car Name': name[0:495],'Variant': variant[0:495],'Distance Travelled': distance[0:495],
                 'Number of Owners': owner[0:495],'fuel type': fuel_type[0:495],'Price': price[0:495]})

<ipython-input-23-2867b21a41f4>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-23-2867b21a41f4>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-23-2867b21a41f4>:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-23-2867b21a41f4>:49: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-23-2867b21a41f4>:60: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-23-2867b21a41f4>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-23-2867b21a41f4>:83: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-23-2867b21a41f4>:94: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [24]:
Chenna

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2020,Hyundai,VENUE,Manual,17570,1st,Petrol,764699
1,2018,Volkswagen,Ameo,Manual,18112,1st,Petrol,553399
2,2011,Toyota,Etios Liva,Manual,87759,2nd,Petrol,324799
3,2015,Honda,CRV,Manual,80621,1st,Petrol,1151099
4,2015,Honda,Amaze,Manual,96366,1st,Petrol,434599
...,...,...,...,...,...,...,...,...
490,2016,Maruti,Swift,Manual,10753,1st,Petrol,470199
491,2013,Maruti,Swift,Manual,99743,1st,Diesel,383899
492,2011,Hyundai,i10,Manual,99023,1st,Petrol,295399
493,2014,Hyundai,Eon,Manual,48000,1st,Petrol,310999
494,2014,Hyundai,i10,Manual,43000,1st,Petrol,366099

In [25]:
# V. Gurgaon location
loc5=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[4]/a")
loc5.click()

<ipython-input-25-228858f6e5e8>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc5=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[4]/a")

In [26]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [28]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Gurga=pd.DataFrame({'Model Year': model_num[0:635],'Brand': brand[0:635],
                 'Car Name': name[0:635],'Variant': variant[0:635],'Distance Travelled': distance[0:635],
                 'Number of Owners': owner[0:635],'fuel type': fuel_type[0:635],'Price': price[0:635]})

<ipython-input-28-ca26a941f32c>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-28-ca26a941f32c>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-28-ca26a941f32c>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-28-ca26a941f32c>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-28-ca26a941f32c>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-28-ca26a941f32c>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-28-ca26a941f32c>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-28-ca26a941f32c>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [29]:
Gurga

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift Dzire,Manual,118117,1st,Diesel,316399
1,2012,Volvo,S60,Automatic,41361,2nd,Diesel,940799
2,2012,Maruti,Swift,Manual,68206,2nd,Diesel,369999
3,2013,Maruti,Ertiga,Manual,119067,3rd,Diesel,438899
4,2013,Maruti,Swift Dzire,Manual,111192,1st,Diesel,379699
...,...,...,...,...,...,...,...,...
630,2017,Maruti,Ertiga,Manual,118264,1st,Diesel,657999
631,2017,Maruti,Wagon R 1.0,Manual,40513,1st,Petrol,394199
632,2019,Maruti,Alto,Manual,43183,1st,Petrol,289099
633,2017,Maruti,Alto 800,Manual,46246,1st,Petrol,299199
634,2020,Hyundai,Creta,Manual,30097,1st,Diesel,993099

In [40]:
# VI. Hyderabad location
loc6=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[5]/a")
loc6.click()

<ipython-input-40-8da2ac89f001>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc6=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[5]/a")

In [41]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [42]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Hyde=pd.DataFrame({'Model Year': model_num[0:100],'Brand': brand[0:100],
                 'Car Name': name[0:100],'Variant': variant[0:100],'Distance Travelled': distance[0:100],
                 'Number of Owners': owner[0:100],'fuel type': fuel_type[0:100],'Price': price[0:100]})

<ipython-input-42-144813130f39>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-42-144813130f39>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-42-144813130f39>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-42-144813130f39>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-42-144813130f39>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-42-144813130f39>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-42-144813130f39>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-42-144813130f39>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [43]:
Hyde

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2018,Maruti,Alto K10,Manual,32851,1st,Petrol,362199
1,2015,Toyota,Innova,Manual,144861,2nd,Diesel,931499
2,2016,Maruti,Baleno,Manual,103172,1st,Petrol,636799
3,2015,Maruti,Celerio,Manual,102472,1st,Petrol,362299
4,2017,Honda,Jazz,Manual,75366,2nd,Petrol,604099
...,...,...,...,...,...,...,...,...
95,2018,Hyundai,Verna,Automatic,32419,1st,Diesel,1114199
96,2017,Honda,City,Automatic,64208,1st,Petrol,863499
97,2018,Honda,WR-V,Manual,13989,1st,Petrol,852699
98,2014,Hyundai,Grand i10,Manual,106258,1st,Diesel,481799
99,2012,Maruti,Swift Dzire,Manual,61660,1st,Petrol,459299

In [50]:
# VII. Mumbai location
loc8=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[7]/a")
loc8.click()

<ipython-input-50-d2ae2de20661>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc8=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[7]/a")

In [51]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [52]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Mumb=pd.DataFrame({'Model Year': model_num[0:1030],'Brand': brand[0:1030],
                 'Car Name': name[0:1030],'Variant': variant[0:1030],'Distance Travelled': distance[0:1030],
                 'Number of Owners': owner[0:1030],'fuel type': fuel_type[0:1030],'Price': price[0:1030]})

<ipython-input-52-f762d138eb3c>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-52-f762d138eb3c>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-52-f762d138eb3c>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-52-f762d138eb3c>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-52-f762d138eb3c>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-52-f762d138eb3c>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-52-f762d138eb3c>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-52-f762d138eb3c>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [53]:
Mumb

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2017,Tata,NEXON,Manual,18019,2nd,Petrol,727899
1,2018,Tata,NEXON,Manual,96906,1st,Diesel,748099
2,2015,Hyundai,i20 Active,Manual,45786,1st,Petrol,540499
3,2016,Hyundai,Elite i20,Manual,88342,2nd,Petrol,497299
4,2015,Maruti,S Cross,Manual,75162,1st,Diesel,572999
...,...,...,...,...,...,...,...,...
1025,2016,Maruti,Wagon R 1.0,Automatic,59288,2nd,Petrol,417599
1026,2016,Renault,Kwid,Manual,30377,1st,Petrol,309599
1027,2016,Maruti,Celerio,Automatic,34999,2nd,Petrol,383799
1028,2017,Hyundai,Verna,Manual,32920,1st,Petrol,755699
1029,2014,Ford,Ecosport,Manual,57108,1st,Diesel,533599

In [54]:
# VIII. Noida location
loc9=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[9]/a")
loc9.click()

<ipython-input-54-6da382fe18ee>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc9=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[9]/a")

In [55]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [57]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Noid=pd.DataFrame({'Model Year': model_num[0:620],'Brand': brand[0:620],
                 'Car Name': name[0:620],'Variant': variant[0:620],'Distance Travelled': distance[0:620],
                 'Number of Owners': owner[0:620],'fuel type': fuel_type[0:620],'Price': price[0:620]})

<ipython-input-57-b7b3bc7469c9>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-57-b7b3bc7469c9>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-57-b7b3bc7469c9>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-57-b7b3bc7469c9>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-57-b7b3bc7469c9>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-57-b7b3bc7469c9>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-57-b7b3bc7469c9>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-57-b7b3bc7469c9>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [58]:
Noid

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift,Manual,82702,1st,Diesel,311999
1,2018,Maruti,Alto 800,Manual,29031,1st,Petrol,295599
2,2013,Maruti,Swift,Manual,114506,1st,Diesel,341599
3,2014,Maruti,Ritz,Manual,43382,1st,Diesel,344199
4,2013,Hyundai,i20,Manual,64361,1st,Diesel,355799
...,...,...,...,...,...,...,...,...
615,2015,Maruti,Swift,Manual,34459,1st,Petrol,455699
616,2017,Ford,Ecosport,Manual,40392,1st,Petrol + CNG,622399
617,2018,Maruti,Vitara Brezza,Manual,54715,2nd,Diesel,731699
618,2017,Hyundai,Eon,Manual,13373,2nd,Petrol,287399
619,2013,Maruti,Swift,Manual,27428,1st,Petrol,371599

In [59]:
# IX. Pune location
loc10=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[10]/a")
loc10.click()

<ipython-input-59-42e8aed780ff>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc10=driver.find_element_by_xpath("//div[@class='col'][2]/ul/li[10]/a")

In [60]:
#scrolling down:
for _ in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [61]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    
#extracting number of owners
try:
    owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in owner_tags:
        owners=i.text.split(' ')[0]
        owner.append(owners)
    owner[0:]
except NoSuchElementException:
    owner.append('-')
    
#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)
    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)


Pun=pd.DataFrame({'Model Year': model_num[0:1030],'Brand': brand[0:1030],
                 'Car Name': name[0:1030],'Variant': variant[0:1030],'Distance Travelled': distance[0:1030],
                 'Number of Owners': owner[0:1030],'fuel type': fuel_type[0:1030],'Price': price[0:1030]})

<ipython-input-61-5d7be5bbfa4c>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-61-5d7be5bbfa4c>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-61-5d7be5bbfa4c>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
<ipython-input-61-5d7be5bbfa4c>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//p[@class='cvakB']/span")
<ipython-input-61-5d7be5bbfa4c>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
<ipython-input-61-5d7be5bbfa4c>:72: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  owner_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
<ipython-input-61-5d7be5bbfa4c>:82: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
<ipython-input-61-5d7be5bbfa4c>:93: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")

In [62]:
Pun

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Volkswagen,Polo,Manual,67595,2nd,Diesel,258399
1,2011,Honda,City,Manual,101973,2nd,Petrol,306899
2,2015,Maruti,Ciaz,Manual,125499,1st,Diesel,589299
3,2014,Maruti,Wagon R Stingray,Manual,81428,2nd,Petrol,332099
4,2013,Maruti,Alto K10,Manual,41769,2nd,Petrol,228999
...,...,...,...,...,...,...,...,...
1025,2014,Maruti,Swift,Manual,143871,1st,Diesel,481499
1026,2019,Maruti,Vitara Brezza,Automatic,69807,1st,Diesel,925099
1027,2015,Maruti,Alto K10,Manual,9226,1st,Petrol,358399
1028,2016,Ford,Figo Aspire,Automatic,26527,1st,Petrol,551899
1029,2009,Toyota,Innova,Manual,182019,2nd,Diesel,438099

In [76]:
Pun.dtypes

Model Year            object
Brand                 object
Car Name              object
Variant               object
Distance Travelled    object
Number of Owners      object
fuel type             object
Price                 object
dtype: object

In [81]:
frames=[NDel1,Ahmed1,Bengl1,Chenna,Gurga,Hyde,Mumb,Noid,Pun]

In [82]:
df1 = pd.concat(frames, sort=False)

In [83]:
df1

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift Dzire,Manual,118117,1st,Diesel,316399
1,2016,Renault,Kwid,Manual,46028,2nd,Petrol,277599
2,2013,Maruti,Swift,Manual,114506,1st,Diesel,341599
3,2014,Maruti,Ritz,Manual,43382,1st,Diesel,344199
4,2013,Hyundai,i20,Manual,64361,1st,Diesel,355799
...,...,...,...,...,...,...,...,...
1025,2014,Maruti,Swift,Manual,143871,1st,Diesel,481499
1026,2019,Maruti,Vitara Brezza,Automatic,69807,1st,Diesel,925099
1027,2015,Maruti,Alto K10,Manual,9226,1st,Petrol,358399
1028,2016,Ford,Figo Aspire,Automatic,26527,1st,Petrol,551899
1029,2009,Toyota,Innova,Manual,182019,2nd,Diesel,438099

In [77]:
#website url of CARDEKHO
driver.get("https://www.cardekho.com/")

In [78]:
button_used=driver.find_element_by_xpath("//span[@class='used-cars-india']")
button_used.click()

<ipython-input-78-b450ad63d723>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  button_used=driver.find_element_by_xpath("//span[@class='used-cars-india']")

In [79]:
button_u=driver.find_element_by_xpath("//a[@title='Used cars in  Ahmedabad']")
button_u.click()

<ipython-input-79-a9deb0594481>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  button_u=driver.find_element_by_xpath("//a[@title='Used cars in  Ahmedabad']")

In [80]:
#scrolling down:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,1000000)")

In [89]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]



#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(150):
        owner.append('1st')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Ahmed2=pd.DataFrame({'Model Year': model_num[0:150],'Brand': brand[0:150],
                 'Car Name': name[0:150],'Variant': variant[0:150],'Distance Travelled': distance[0:150],
                 'Number of Owners': owner[0:150],'fuel type': fuel_type[0:150],'Price': price[0:150]})

<ipython-input-89-c27312070d56>:15: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-89-c27312070d56>:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-89-c27312070d56>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-89-c27312070d56>:50: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-89-c27312070d56>:61: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-89-c27312070d56>:75: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-89-c27312070d56>:97: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [91]:
Ahmed2

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift Dzire,manual,80134,1st,Diesel,313000
1,2019,Maruti,S-Presso,manual,24268,1st,Petrol,369500
2,2019,Maruti,Swift Dzire,manual,11935,1st,Petrol,680000
3,2016,Maruti,Eeco,manual,45384,1st,Petrol,299500
4,2018,Volkswagen,Vento,manual,98027,1st,Diesel,786500
...,...,...,...,...,...,...,...,...
145,2018,Maruti,Alto 800,manual,35000,1st,Petrol,320000
146,2017,Hyundai,Creta,automatic,110000,1st,Diesel,900000
147,2010,Mahindra,Bolero,manual,120000,1st,Diesel,315000
148,2015,Honda,Amaze,automatic,120000,1st,Petrol,399999
149,2015,Renault,Lodgy,manual,70000,1st,Diesel,565000

In [92]:
driver.get("https://www.cardekho.com/used-cars+in+ahmedabad+second-owner")

In [93]:
#scrolling down:
for _ in range(50000):
    driver.execute_script("window.scrollBy(0,1000000)")

In [97]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]



#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(80):
        owner.append('2nd')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Ahmed3=pd.DataFrame({'Model Year': model_num[0:80],'Brand': brand[0:80],
                 'Car Name': name[0:80],'Variant': variant[0:80],'Distance Travelled': distance[0:80],
                 'Number of Owners': owner[0:80],'fuel type': fuel_type[0:80],'Price': price[0:80]})

<ipython-input-97-06d974a54047>:15: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-97-06d974a54047>:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-97-06d974a54047>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-97-06d974a54047>:50: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-97-06d974a54047>:61: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-97-06d974a54047>:75: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-97-06d974a54047>:97: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [99]:
Ahmed3

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2015,Toyota,Fortuner,manual,196000,2nd,Diesel,1550000
1,2012,Mahindra,XUV500,manual,134011,2nd,Diesel,360000
2,2007,Honda,City,manual,151000,2nd,Petrol,150000
3,2014,Mahindra,Quanto,manual,100000,2nd,Diesel,270000
4,2014,Maruti,Ciaz,manual,52000,2nd,Petrol,525000
...,...,...,...,...,...,...,...,...
75,2010,Honda,City,manual,71901,2nd,Petrol,500000
76,2012,Volkswagen,Vento,manual,63940,2nd,Diesel,351000
77,2015,Mahindra,XUV500,automatic,77708,2nd,Diesel,800000
78,2014,Hyundai,Elantra,automatic,65221,2nd,Diesel,575000
79,2009,Maruti,Swift,manual,75000,2nd,Petrol,265000

In [133]:
#Mumbai loc:
try: 
    locv=driver.find_element_by_xpath("//a[@title='Used cars in Mumbai']")
    locv.click()
except:
    driver.get("https://www.cardekho.com/used-cars+in+mumbai")

<ipython-input-133-413907a0b2f4>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  locv=driver.find_element_by_xpath("//a[@title='Used cars in Mumbai']")

In [111]:
driver.get("https://www.cardekho.com/used-cars+in+mumbai+first-owner")

In [112]:
#scrolling down:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,100000000)")

In [114]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(300):
        owner.append('1st')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Mum1=pd.DataFrame({'Model Year': model_num[0:300],'Brand': brand[0:300],
                 'Car Name': name[0:300],'Variant': variant[0:300],'Distance Travelled': distance[0:300],
                 'Number of Owners': owner[0:300],'fuel type': fuel_type[0:300],'Price': price[0:300]})

<ipython-input-114-40f468d1116a>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-114-40f468d1116a>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-114-40f468d1116a>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-114-40f468d1116a>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-114-40f468d1116a>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-114-40f468d1116a>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-114-40f468d1116a>:95: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [115]:
Mum1

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2013,Hyundai,Verna,manual,77056,1st,Petrol,455000
1,2015,Honda,Amaze,manual,68378,1st,Petrol,391000
2,2015,Maruti,Ciaz,manual,73781,1st,Diesel,642000
3,2015,Maruti,Ciaz,manual,107972,1st,Petrol,525000
4,2017,Maruti,Baleno,manual,11755,1st,Petrol,628000
...,...,...,...,...,...,...,...,...
295,2017,Hyundai,i20,manual,52710,1st,Diesel,650000
296,2020,Renault,KWID,automatic,12355,1st,Petrol,429000
297,2015,Maruti,Ciaz,manual,87028,1st,Diesel,540000
298,2018,Maruti,Baleno,manual,77884,1st,Petrol,580000
299,2017,Maruti,Swift Dzire,automatic,51314,1st,Diesel,681500

In [134]:
driver.get("https://www.cardekho.com/used-cars+in+mumbai+second-owner")

In [136]:
#scrolling down:
for _ in range(20000):
    driver.execute_script("window.scrollBy(0,800000000)")

In [137]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(400):
        owner.append('2nd')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Mum2=pd.DataFrame({'Model Year': model_num[0:400],'Brand': brand[0:400],
                 'Car Name': name[0:400],'Variant': variant[0:400],'Distance Travelled': distance[0:400],
                 'Number of Owners': owner[0:400],'fuel type': fuel_type[0:400],'Price': price[0:400]})

<ipython-input-137-1f36b05f53a2>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-137-1f36b05f53a2>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-137-1f36b05f53a2>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-137-1f36b05f53a2>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-137-1f36b05f53a2>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-137-1f36b05f53a2>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-137-1f36b05f53a2>:95: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [138]:
Mum2

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2019,Renault,KWID,manual,3217,2nd,Petrol,343000
1,2014,Honda,Brio,automatic,31655,2nd,Petrol,411000
2,2015,Hyundai,Grand i10,manual,80883,2nd,Petrol,366000
3,2016,Honda,City,manual,23541,2nd,Petrol,723000
4,2017,Maruti,Wagon R,automatic,64207,2nd,Petrol,389000
...,...,...,...,...,...,...,...,...
395,2018,Tata,Tiago,manual,21016,2nd,Petrol,435000
396,2016,Hyundai,Creta,manual,48000,2nd,Petrol,790000
397,2016,Renault,KWID,manual,26000,2nd,Petrol,299000
398,2012,Hyundai,i20,manual,81000,2nd,Diesel,325000
399,2015,Mahindra,XUV500,manual,48000,2nd,Diesel,890000

In [123]:
# Pune loc:
try: 
    locp=driver.find_element_by_xpath("//a[@title='Used cars in Pune']")
    locp.click()
except:
    driver.get("https://www.cardekho.com/used-cars+in+pune")

<ipython-input-123-8acb19d2275e>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  locp=driver.find_element_by_xpath("//a[@title='Used cars in Pune']")

In [124]:
#1st owner filter:
driver.get("https://www.cardekho.com/used-cars+in+pune+first-owner")

In [125]:
#scrolling down:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,900000000)")

In [126]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(500):
        owner.append('1st')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Pun2=pd.DataFrame({'Model Year': model_num[0:500],'Brand': brand[0:500],
                 'Car Name': name[0:500],'Variant': variant[0:500],'Distance Travelled': distance[0:500],
                 'Number of Owners': owner[0:500],'fuel type': fuel_type[0:500],'Price': price[0:500]})

<ipython-input-126-cf0d046d1676>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-126-cf0d046d1676>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-126-cf0d046d1676>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-126-cf0d046d1676>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-126-cf0d046d1676>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-126-cf0d046d1676>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-126-cf0d046d1676>:95: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [128]:
Pun2

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2013,Honda,Amaze,manual,61079,1st,Diesel,399000
1,2017,Maruti,Ignis,manual,40364,1st,Petrol,489000
2,2018,Hyundai,EON,manual,29213,1st,Petrol,354000
3,2018,Tata,Tiago,automatic,46985,1st,Petrol,515000
4,2018,Tata,Hexa,manual,20584,1st,Diesel,1070500
...,...,...,...,...,...,...,...,...
495,2016,Maruti,Wagon R,automatic,62100,1st,Petrol,395000
496,2014,Hyundai,EON,manual,44000,1st,Petrol,255000
497,2018,Maruti,Vitara Brezza,manual,58000,1st,Diesel,855000
498,2017,Hyundai,Grand i10,manual,71234,1st,Petrol,460000
499,2014,Tata,Nano,manual,18070,1st,Petrol,145000

In [129]:
# 2nd owner filter:
driver.get("https://www.cardekho.com/used-cars+in+pune+second-owner")

In [130]:
#scrolling down:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,900000000)")

In [131]:
# defining variable
model_num=[]
brand=[]
name=[]
variant=[]
distance=[]
owner=[]
fuel_type=[]
price=[]

#extracting model_num
try:
    model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in model_tags:
        models=i.text.split(' ')[0]
        model_num.append(models)
    model_num[0:]
except NoSuchElementException:
    model_num.append('-')
    
#extracting car brand
try:
    brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    #battery=[]
    for i in brand_tags:
        brands=i.text.split(' ')[1:2]
        b="[]".join(brands)
        brand.append(b)
    brand[0:]
except NoSuchElementException:
    brand.append('-')
time.sleep(1)

#extracting car name
try:
    name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
    for i in name_tags:
        names=i.text.split(' ')[2:]
        l=" ".join(names)
        name.append(l)
    name[0:]
except NoSuchElementException:
    name.append('-')
time.sleep(1)

#extracting car variant
try:
    variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
    for i in variant_tags:
        variants=i.text
        variant.append(variants)
    variant[0:]
except NoSuchElementException:
    variant.append('-')
time.sleep(1)
    
#extracting distance travelled
try:
    distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
    for i in distance_tags:
        distances=i.text.split(' ')[0]
        d=distances.replace(',','')
        #d=" ".join(distances)
        distance.append(d)
    distance[0:]
except NoSuchElementException:
    distance.append('-')
time.sleep(1)
    

#extracting fuel type
try:
    fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
    for i in fuel_tags:
        #fuels=i.text
        fuel_type.append(i.text)
    fuel_type[0:]
except NoSuchElementException:
    fuel_type.append('-')
time.sleep(1)

#extracting number of owners

try:
    for i in range(290):
        owner.append('2nd')
    owner[0:]
except NoSuchElementException:
    owner.append('-')
time.sleep(1)

    
#extracting price
try:
    price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")
    for i in price_tags:
        prices=i.text.replace('₹','')
        p=prices.replace(',','')
        price.append(p)
    price[0:]
except NoSuchElementException:
    price.append('-')
time.sleep(1)



Pun3=pd.DataFrame({'Model Year': model_num[0:290],'Brand': brand[0:290],
                 'Car Name': name[0:290],'Variant': variant[0:290],'Distance Travelled': distance[0:290],
                 'Number of Owners': owner[0:290],'fuel type': fuel_type[0:290],'Price': price[0:290]})

<ipython-input-131-691e34ea49ef>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  model_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-131-691e34ea49ef>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  brand_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-131-691e34ea49ef>:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
<ipython-input-131-691e34ea49ef>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  variant_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[3]")
<ipython-input-131-691e34ea49ef>:59: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  distance_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[1]")
<ipython-input-131-691e34ea49ef>:73: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  fuel_tags=driver.find_elements_by_xpath("//div[@class='truncate dotlist']/span[2]")
<ipython-input-131-691e34ea49ef>:95: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  price_tags=driver.find_elements_by_xpath("//div[@class='gsc_col-xs-5 text-right price']/span")

In [132]:
Pun3

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2016,Hyundai,Creta,automatic,89154,2nd,Diesel,1017500
1,2015,Honda,CR-V,automatic,87126,2nd,Petrol,991000
2,2018,Maruti,Baleno,automatic,24233,2nd,Petrol,714500
3,2018,Toyota,Yaris,manual,19482,2nd,Petrol,829000
4,2012,Maruti,Swift,manual,62193,2nd,Petrol,366000
...,...,...,...,...,...,...,...,...
285,2017,Honda,Brio,automatic,27500,2nd,Petrol,600000
286,2014,Land,Rover Freelander 2,automatic,80000,2nd,Diesel,1850000
287,2012,Ford,Figo,manual,65000,2nd,Diesel,210999
288,2012,Honda,Civic,automatic,87792,2nd,Petrol,425000
289,2013,Audi,A6,automatic,90004,2nd,Diesel,1500000

In [140]:
frames=[NDel1,Ahmed1,Bengl1,Chenna,Gurga,Hyde,Mumb,Noid,Pun,Ahmed2,Ahmed3,Mum1,Mum2,Pun2,Pun3]

In [144]:
df_cars = pd.concat(frames, sort=False)

In [145]:
df_cars

,Model Year,Brand,Car Name,Variant,Distance Travelled,Number of Owners,fuel type,Price
0,2012,Maruti,Swift Dzire,Manual,118117,1st,Diesel,316399
1,2016,Renault,Kwid,Manual,46028,2nd,Petrol,277599
2,2013,Maruti,Swift,Manual,114506,1st,Diesel,341599
3,2014,Maruti,Ritz,Manual,43382,1st,Diesel,344199
4,2013,Hyundai,i20,Manual,64361,1st,Diesel,355799
...,...,...,...,...,...,...,...,...
285,2017,Honda,Brio,automatic,27500,2nd,Petrol,600000
286,2014,Land,Rover Freelander 2,automatic,80000,2nd,Diesel,1850000
287,2012,Ford,Figo,manual,65000,2nd,Diesel,210999
288,2012,Honda,Civic,automatic,87792,2nd,Petrol,425000
289,2013,Audi,A6,automatic,90004,2nd,Diesel,1500000

## DataFrame to Excel file:

In [148]:
# Cras_Data Excel file created and saved in Desktop

df_cars.to_excel("C:\\Users\\hp\\Desktop\\Cars_Data.xlsx")